recipex_auth:
    resource: "@RecipexAuthBundle/Resources/config/routing.yml"
    prefix:   /api/v1/auth

recipex_core:
    resource: "@RecipexCoreBundle/Resources/config/routing.yml"
    prefix:   /api/v1
