services:
    recipex_core.api_problem_subscriber:
        class: Recipex\CoreBundle\EventListener\ApiExceptionSubscriber
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
