services:
    recipex_core.api_problem_subscriber:
        class: Recipex\CoreBundle\EventListener\ApiExceptionSubscriber
        arguments: [%kernel.debug%]
        tags:
            - { name: kernel.event_subscriber }

    recipex_core.form.registration:
        class: Recipex\CoreBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: recipex_core_user_registration }
