services:
    recipex_core.api_problem_subscriber:
        class: Recipex\CoreBundle\EventListener\ApiExceptionSubscriber
        arguments: [%kernel.debug%]
        tags:
            - { name: kernel.event_subscriber }
